name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: nhe0622/gitme
          stage: main
          yaml: |
            name: gitme-server
            app: java@17
            options:
               env:
                 - name: GITHUB_CLIENT_ID
                   secret: GITHUB_CLIENT_ID
                 - name: GITHUB_CLIENT_SECRET
                   secret: GITHUB_CLIENT_SECRET
                 - name: KAKAO_CLIENT_ID
                   secret: KAKAO_CLIENT_ID
                 - name: KAKAO_CLIENT_SECRET
                   secret: KAKAO_CLIENT_SECRET
                 - name: KAKAO_REDIRECT_URL
                   secret: KAKAO_REDIRECT_URL
                 - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
                   secret: SPRING_DATASOURCE_DRIVER_CLASS_NAME
                 - name: SPRING_DATASOURCE_PASSWORD
                   secret: SPRING_DATASOURCE_PASSWORD
                 - name: SPRING_DATASOURCE_URL
                   secret: SPRING_DATASOURCE_URL
                 - name: SPRING_DATASOURCE_USERNAME
                   secret: SPRING_DATASOURCE_USERNAME
              ports: "8080"
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}